apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etc-role-binding-hack
  namespace: openshift-etcd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: Group
  name: opsp_develauctiondev_rusr_opql
