apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apache-app-role-binding-group-s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: Group
  name: opsp_develsbmsdev_rusr_opql
